---
# tasks file for roles/db
- name: Run DB container
  docker_container:
      name: postgres-db-tp1
      image: b0x550xaat/postgres-db-tp1
      state: started
      recreate: true
      pull: true
      networks:
          - name: hehe-network
      env:
          POSTGRES_PASSWORD: "{{POSTGRES_PASSWORD}}"
          POSTGRES_USER: "{{POSTGRES_USER}}"
          POSTGRES_DB: "{{POSTGRES_DB}}"
      volumes:
          - local_db:/var/lib/postgresql/data
