---
# tasks file for roles/backend-api
- name: Install Backend API
  docker_container:
      name: backend-api-tp1
      image: b0x550xaat/backend-api-tp1
      recreate: true
      pull: true
      networks:
          - name: hehe-network
      env:
          POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
          POSTGRES_USER: "{{ POSTGRES_USER }}"
          POSTGRES_DB: "{{ POSTGRES_DB }}"
